# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SOPT_5th' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SOPT_5th
    pod 'Tabman', '~> 2.6'
    pod 'Alamofire', '~> 4.8.2'

end
