# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'study_Alamofire' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for study_Alamofire
  # Pods for testing
  pod 'Alamofire', '~> 4.8.2'
 
end
